#REPO_PATH: "/Users/tylerband/CALiveAPICreator.repository/teamspaces/default/apis/demo/rules/demo/customer"

#DB_DRIVER: postgres
#DB_SOURCE: postgresql://admin:password@localhost:5432/postgres?sslmode=disable
#SERVER_ADDRESS: 0.0.0.0:8090

server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
repos:
  project: "demo"
  path: "/Users/tylerband/CALiveAPICreator.repository/teamspaces/default/apis/demo/rules"